---
name: 'github-actions-dummy'
description: 'https://github.com/garethjevans/github-actions-dummy'
branding:
  icon: 'tag'
  color: 'blue'
inputs:
outputs:
runs:
  using: 'docker'
  image: 'docker://ghcr.io/garethjevans/github-actions-dummy:v0.0.7'
  entrypoint: 'github-actions-entrypoint.sh'
